name: lineage-build

on:
  push:
    branches:
      - master

env:
  VERSION: lineage-22.1
  DEVICE: onclite
  TYPE: user
  RELEASE_TYPE: release
  EXP_PICK_CHANGES: ""

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: Build 
      run: |
        sudo apt-get install repo
        export BUILD_NUMBER=$( (date +%s%N ; echo $CI_PIPELINE_ID; hostname) | openssl sha1 | sed -e 's/.*=//g; s/ //g' | cut -c1-10 )
        repo init --depth 1 -u https://github.com/lineageos/android.git -b ${VERSION}
        echo "Syncing"
        repo sync -c -j$(nproc)
        echo "Sourcing the environment"
        . build/envsetup.sh
        echo "Eating breakfast"
        breakfast lineage_${DEVICE}-${TYPE}
        tree -a --prune -o current_working_tree.txt

    - name: Build 
      run: |
        pip install -r requirements.txt
        python sign.py
